name: soundhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  dio: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/artistas/
    - assets/albuns/
    - assets/albuns/TaylorSwift/
    - assets/albuns/TheWeeknd/
    - assets/albuns/EdSheeran/
    - assets/albuns/BrunoMars/
    - assets/albuns/Nirvana/
    - assets/albuns/Beatles/
    - assets/albuns/PinkFloyd/
    - assets/albuns/Eagles/
    - assets/albuns/MatheusKauan/
    - assets/albuns/JorgeMateus/
    - assets/albuns/WesleySafadao/
    - assets/albuns/MariliaMendonca/
